version: '3.7'
services:
  back:
    build:
      dockerfile: './nest.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '10022:22'
      - '13000:3000'
    volumes:
      - './back:/back'

  front:
    build:
      dockerfile: './nuxt.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '11080:80'
      - '11022:22'
      - '3000:3001'
    volumes:
      - './front:/front'
      - './default:/etc/nginx/sites-available/default'

  db:
    build:
      dockerfile: './db.Dockerfile'
    ports:
      - '13306:3306'
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=docker123
      - TZ=Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql