version: '3.7'
services:
  nest:
    build:
      dockerfile: './nest.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '22:22'
      - '3000:3000'
    volumes:
      - './app:/app'
  db:
    build:
      dockerfile: './db.Dockerfile'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=docker123
      - TZ=Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql